/*
CREATE TABLE IF NOT EXISTS USER_INFO (
    ID VARCHAR(20) NOT NULL PRIMARY KEY,
    PW VARCHAR(20),
    EMAIL VARCHAR(255)
);





CREATE TABLE TB_DOG_TABLE (
  DOG_NO BIGINT PRIMARY KEY AUTO_INCREMENT,
  HOS_NO INT DEFAULT '0',
  D_ALL_TEST VARCHAR(50) DEFAULT '0',
  D_BLOOD_TEST VARCHAR(50) DEFAULT '0',
  D_ULTRASONOGRAPHY VARCHAR(50) DEFAULT '0',
  D_XRAY VARCHAR(50) DEFAULT '0',
  D_ALLERGY VARCHAR(50) DEFAULT '0',
  DHEARTBUG_KIT VARCHAR(50) DEFAULT '0',
  D_BASIC_PHYSICAL_TEST VARCHAR(50) DEFAULT '0',
  D_1 VARCHAR(50) DEFAULT '0',
  D_2 VARCHAR(50) DEFAULT '0',
  D_3 VARCHAR(50) DEFAULT '0',
  D_4 VARCHAR(50) DEFAULT '0',
  D_5 VARCHAR(50) DEFAULT '0',
  D_6 VARCHAR(50) DEFAULT '0',
  D_CIPM VARCHAR(50) DEFAULT '0',
  D_ANTIBODY_TEST VARCHAR(50) DEFAULT '0',
  D_BOOST_ERVCC VARCHAR(50) DEFAULT '0',
  D_BLADDER_STONE VARCHAR(50) DEFAULT '0',
  D_YODO_STONE VARCHAR(50) DEFAULT '0',
  D_BREAST_TUMOR VARCHAR(50) DEFAULT '0',
  D_PYOMETRA VARCHAR(50) DEFAULT '0',
  D_ETC_TUMORS VARCHAR(50) DEFAULT '0',
  D_LEG_TEST VARCHAR(50) DEFAULT '0',
  D_PATELLA_DISLOCATION VARCHAR(50) DEFAULT '0',
  D_FEMORAL_HEAD VARCHAR(50) DEFAULT '0',
  D_ACL VARCHAR(50) DEFAULT '0',
  D_THROW_UP VARCHAR(50) DEFAULT '0',
  D_DIARRHEA VARCHAR(50) DEFAULT '0',
  D_BLOOD_POOP VARCHAR(50) DEFAULT '0',
  D_BASIC_CARE VARCHAR(50) DEFAULT '0',
  D_EYE_CARE VARCHAR(50) DEFAULT '0',
  D_CHERRY_EYE VARCHAR(50) DEFAULT '0',
  D_TNRM VARCHAR(50) DEFAULT '0',
  D_TNRW VARCHAR(50) DEFAULT '0',
  D_SCALING VARCHAR(50) DEFAULT '0',
  D_ALL_TOOTH VARCHAR(50) DEFAULT '0',
  D_MILK_TOOTH VARCHAR(50) DEFAULT '0',
  D_DENTAL_CARE VARCHAR(50) DEFAULT '0',
  D_FOREVER_TOOTH VARCHAR(50) DEFAULT '0',
  D_HERNIA VARCHAR(50) DEFAULT '0',
  D_SKIN_CARE VARCHAR(50) DEFAULT '0'
);
*/